#' Example Isoform Structures
#'
#' Pre-computed isoform structures from a 5-gene subset of GENCODE v49.
#' Contains ~25 isoforms from SRSF3, SRSF1, BCL2L1, TP63, and FAM13A.
#' Generated by [parseIsoformStructures()] from `example_small.gtf`.
#'
#' @format A tibble with columns:
#' \describe{
#'   \item{isoform_id}{Transcript ID (ENST format)}
#'   \item{gene_id}{Gene ID (ENSG format)}
#'   \item{chr}{Chromosome}
#'   \item{strand}{"+" or "-"}
#'   \item{n_exons}{Number of exons}
#'   \item{exon_starts}{List of exon start positions}
#'   \item{exon_ends}{List of exon end positions}
#'   \item{tx_start}{Transcript start coordinate}
#'   \item{tx_end}{Transcript end coordinate}
#'   \item{n_junctions}{Number of splice junctions}
#' }
#' @source GENCODE v49 primary assembly annotation.
#' @examples
#' data(example_structures)
#' head(example_structures)
"example_structures"


#' Example Isoform Pairs
#'
#' Pre-computed isoform pairs generated by [generatePairsExpression()] using
#' the top-two method on mock expression data for 5 genes.
#'
#' @format A tibble with columns:
#' \describe{
#'   \item{gene_id}{Gene ID}
#'   \item{reference_isoform_id}{Reference (highest expressed) isoform ID}
#'   \item{comparator_isoform_id}{Comparator (second highest) isoform ID}
#'   \item{source}{"expression" for all rows}
#'   \item{direction}{NA for expression-derived pairs}
#'   \item{logFC}{NA for expression-derived pairs}
#'   \item{adj_p_val}{NA for expression-derived pairs}
#' }
#' @source Generated from mock expression data and GENCODE v49 annotations.
#' @examples
#' data(example_pairs)
#' head(example_pairs)
"example_pairs"


#' Example Splicing Choice Profiles
#'
#' Pre-computed splicing choice profiles from [buildProfiles()], using
#' [example_pairs] and [example_structures]. Each row describes the
#' structural differences between one isoform pair.
#'
#' @format A tibble with one row per pair and columns including:
#' \describe{
#'   \item{gene_id}{Gene ID}
#'   \item{reference_isoform_id}{Reference isoform ID}
#'   \item{comparator_isoform_id}{Comparator isoform ID}
#'   \item{n_events}{Total number of detected events}
#'   \item{n_a5ss, n_a3ss, n_se, ...}{Counts per event type}
#'   \item{bp_gain, bp_loss, net_bp}{Basepair gain/loss metrics}
#'   \item{junction_similarity}{Jaccard similarity of splice junctions}
#'   \item{detailed_events}{Nested tibble of detected events}
#'   \item{reconstruction_status}{"PASS", "FAIL", or "ERROR"}
#' }
#' @source Generated from [example_pairs] and [example_structures].
#' @examples
#' data(example_profiles)
#' summarizeProfiles(example_profiles)
"example_profiles"
